package com.tlotlanang.virtualstockexchangebackend.User.CompanyListing.CompanySelectbanker.mapper;

import com.tlotlanang.virtualstockexchangebackend.User.CompanyListing.CompanySelectbanker.domain.CompanyViewsBankerDto;
import com.tlotlanang.virtualstockexchangebackend.User.CompanyListing.CompanySelectbanker.domain.CompanyViewsBankersRequest;
import com.tlotlanang.virtualstockexchangebackend.User.CompanyListing.CompanySelectbanker.domain.CompanyViewsBankersResponseDto;
import com.tlotlanang.virtualstockexchangebackend.User.CompanyListing.CompanySelectbanker.entity.CompanyViewsBankersEntity;

public interface CompanyViewsBankersMapper {

    CompanyViewsBankersRequest fromDto(CompanyViewsBankerDto companyViewsBankerDto);
    CompanyViewsBankersResponseDto toDto(CompanyViewsBankersEntity companyViewsBankersEntity);
}
